export const CATEGORIES = [
  'All', 'Plumbing', 'Electrical', 'AC Repair', 'Painting', 'Cleaning',
];

export const CATEGORY_COLORS = {
  Plumbing: '#2196F3',
  Electrical: '#FF9800',
  Cleaning: '#4CAF50',
  Painting: '#9C27B0',
  'AC Repair': '#00BCD4',
};

export const ANNOUNCEMENTS = [
  {
    id: 'a1',
    icon: '📈',
    title: 'High Demand This Week!',
    titleSi: 'මෙම සතියේ ඉහළ ඉල්ලුම!',
    message: 'Plumbing services are 3x in demand in Colombo. Update your availability now.',
    messageSi: 'කොළඹ නළ සේවා ඉල්ලුම 3x ඉහළ ගොස් ඇත. ඔබේ ලබා ගැනීමේ හැකියාව යාවත්කාලීන කරන්න.',
    color: '#2563EB',
    bg: '#EFF6FF',
  },
  {
    id: 'a2',
    icon: '💡',
    title: 'Pro Tip: Complete Your Profile',
    titleSi: 'ඉඟිය: ඔබේ පැතිකඩ සම්පූර්ණ කරන්න',
    message: 'Providers with full profiles get 40% more job invites.',
    messageSi: 'සම්පූර්ණ පැතිකඩ ඇති සේවා සැපයුම්කරුවන්ට 40% වැඩි රැකියා ලැබේ.',
    color: '#7C3AED',
    bg: '#F5F3FF',
  },
  {
    id: 'a3',
    icon: '🎉',
    title: 'New Feature: AI Bid Generator',
    titleSi: 'නව විශේෂාංගය: AI ඉල්ලුම් ජනකය',
    message: 'Auto-generate winning bid messages with one tap.',
    messageSi: 'එක් තට්ටුවකින් දිනන ඉල්ලුම් පණිවිඩ ස්වයංක්‍රීයව සාදන්න.',
    color: '#059669',
    bg: '#ECFDF5',
  },
];

export const MID_ANNOUNCEMENT = {
  icon: '🔥',
  title: 'Garden Care demand is up 3x in Colombo 07!',
  titleSi: 'කොළඹ 07 හි උද්‍යාන සේවා ඉල්ලුම 3x ඉහළ ගොස් ඇත!',
  message: 'Update your garden service listing to get more bookings this week.',
  messageSi: 'මෙම සතියේ වැඩි වෙන්කිරීම් ලබා ගැනීමට ඔබේ උද්‍යාන සේවා ලැයිස්තුව යාවත්කාලීන කරන්න.',
  color: '#EA580C',
  bg: '#FFF7ED',
};

export const POSTS = [
  {
    id: '1',
    customer: 'Kumara Perera',
    avatar: 'https://randomuser.me/api/portraits/men/32.jpg',
    location: 'Colombo 03',
    time: '10 mins ago',
    category: 'Plumbing',
    description: 'Leaking water main in the garden area. Need urgent repair before tonight.',
    budget: 'LKR 4,500',
    applied: 4,
    views: 28,
    urgent: true,
    aiMatch: 92,
    lang: 'en',
  },
  {
    id: '2',
    customer: 'Anoma Silva',
    avatar: 'https://randomuser.me/api/portraits/women/44.jpg',
    location: 'Kandy Central',
    time: '1 hour ago',
    category: 'Electrical',
    description: 'Installation of three new ceiling fans and replacing old light switches in the living room.',
    budget: 'LKR 8,000',
    applied: 12,
    views: 104,
    urgent: false,
    aiMatch: 78,
    lang: 'en',
  },
  {
    id: '3',
    customer: 'නිමල් පෙරේරා',
    avatar: 'https://randomuser.me/api/portraits/men/55.jpg',
    location: 'කොළඹ 07',
    time: 'පැය 2 කට පෙර',
    category: 'Cleaning',
    description: 'නිවසේ සාලය, කාමර 3ක් සහ නාන කාමර 2ක් ගැඹුරු පිරිසිදු කිරීමක් අවශ්‍යයි.',
    budget: 'LKR 6,000',
    applied: 5,
    views: 32,
    urgent: false,
    aiMatch: null,
    lang: 'si',
  },
  {
    id: '4',
    customer: 'Samira Wickramasinghe',
    avatar: 'https://randomuser.me/api/portraits/women/68.jpg',
    location: 'Negombo',
    time: '3 hours ago',
    category: 'AC Repair',
    description: 'Master bedroom AC unit is not cooling and making a loud rattling noise. Needs servicing.',
    budget: 'LKR 3,500',
    applied: 2,
    views: 15,
    urgent: false,
    aiMatch: null,
    lang: 'en',
  },
  {
    id: '5',
    customer: 'Dilini Fernando',
    avatar: 'https://randomuser.me/api/portraits/women/12.jpg',
    location: 'Mount Lavinia',
    time: '5 hours ago',
    category: 'Painting',
    description: 'Small interior painting job for a 10x12 room. Surface prep and two coats of emulsion needed.',
    budget: 'LKR 12,000',
    applied: 8,
    views: 56,
    urgent: false,
    aiMatch: 85,
    lang: 'en',
  },
];