import { StyleSheet } from 'react-native';

export const decisionMeta = {
  CAN_ACCEPT: {
    bg: '#DCFCE7',
    text: '#166534',
    border: '#86EFAC',
    label: 'Can Accept',
  },
  AVAILABLE_WITH_CAUTION: {
    bg: '#FEF3C7',
    text: '#92400E',
    border: '#FCD34D',
    label: 'Available With Caution',
  },
  RESCHEDULE_REQUIRED: {
    bg: '#FEE2E2',
    text: '#B91C1C',
    border: '#FCA5A5',
    label: 'Reschedule Required',
  },
  REJECTED_DUE_TO_CONFLICT: {
    bg: '#FEE2E2',
    text: '#991B1B',
    border: '#F87171',
    label: 'Rejected Due To Conflict',
  },
  DEFAULT: {
    bg: '#E5E7EB',
    text: '#374151',
    border: '#D1D5DB',
    label: 'Unknown',
  },
};

const styles = StyleSheet.create({
  screen: {
    flex: 1,
    backgroundColor: '#F9FAFB',
  },
  centerWrap: {
    flex: 1,
    alignItems: 'center',
    justifyContent: 'center',
    paddingHorizontal: 20,
  },
  centerText: {
    marginTop: 10,
    color: '#6B7280',
    fontSize: 14,
    textAlign: 'center',
  },
  header: {
    paddingHorizontal: 18,
    paddingVertical: 14,
    borderBottomWidth: 1,
    borderBottomColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'space-between',
  },
  headerTitle: {
    fontSize: 17,
    fontWeight: '700',
    color: '#111827',
  },
  iconButton: {
    width: 36,
    height: 36,
    borderRadius: 18,
    alignItems: 'center',
    justifyContent: 'center',
    backgroundColor: '#EEF2FF',
  },
  body: {
    flex: 1,
    padding: 16,
  },
  card: {
    backgroundColor: '#FFFFFF',
    borderRadius: 14,
    padding: 14,
    marginBottom: 12,
    borderWidth: 1,
    borderColor: '#E5E7EB',
  },
  cardTitle: {
    fontSize: 15,
    fontWeight: '700',
    color: '#111827',
    marginBottom: 10,
  },
  row: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    marginBottom: 8,
  },
  rowLabel: {
    flex: 1,
    color: '#6B7280',
    fontSize: 13,
    marginRight: 8,
  },
  rowValue: {
    flex: 1.2,
    color: '#111827',
    fontSize: 13,
    textAlign: 'right',
  },
  decisionBadge: {
    paddingHorizontal: 10,
    paddingVertical: 6,
    borderRadius: 999,
    borderWidth: 1,
    alignSelf: 'flex-start',
    marginBottom: 10,
  },
  decisionText: {
    fontSize: 12,
    fontWeight: '700',
  },
  infoBox: {
    borderRadius: 10,
    padding: 10,
    borderWidth: 1,
    borderColor: '#D1D5DB',
    backgroundColor: '#F9FAFB',
  },
  infoText: {
    color: '#374151',
    fontSize: 13,
    lineHeight: 19,
  },
  conflictRow: {
    flexDirection: 'row',
    alignItems: 'center',
    marginTop: 8,
    gap: 8,
  },
  conflictText: {
    fontSize: 13,
    fontWeight: '600',
  },
  slotItem: {
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#E5E7EB',
    backgroundColor: '#FFFFFF',
    padding: 10,
    marginTop: 8,
  },
  slotText: {
    color: '#111827',
    fontSize: 13,
  },
  primaryButton: {
    marginTop: 14,
    backgroundColor: '#6366F1',
    borderRadius: 10,
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
  },
  primaryButtonText: {
    color: '#FFFFFF',
    fontWeight: '700',
    fontSize: 14,
  },
  outlineButton: {
    marginTop: 10,
    borderRadius: 10,
    borderWidth: 1,
    borderColor: '#6366F1',
    paddingVertical: 12,
    alignItems: 'center',
    justifyContent: 'center',
    flexDirection: 'row',
    gap: 8,
    backgroundColor: '#FFFFFF',
  },
  outlineButtonText: {
    color: '#6366F1',
    fontWeight: '700',
    fontSize: 14,
  },
  errorCard: {
    borderWidth: 1,
    borderColor: '#FCA5A5',
    backgroundColor: '#FEF2F2',
    borderRadius: 12,
    padding: 12,
    marginBottom: 12,
  },
  errorText: {
    color: '#B91C1C',
    fontSize: 13,
  },
  scheduleItem: {
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 12,
    marginBottom: 10,
  },
  scheduleTop: {
    flexDirection: 'row',
    justifyContent: 'space-between',
    alignItems: 'center',
    marginBottom: 8,
  },
  scheduleTitle: {
    fontSize: 14,
    fontWeight: '700',
    color: '#111827',
    flex: 1,
    marginRight: 8,
  },
  scheduleTime: {
    fontSize: 12,
    color: '#374151',
    marginBottom: 4,
  },
  emptyCard: {
    borderRadius: 12,
    backgroundColor: '#FFFFFF',
    borderWidth: 1,
    borderColor: '#E5E7EB',
    padding: 16,
    alignItems: 'center',
  },
  emptyText: {
    marginTop: 8,
    color: '#6B7280',
    fontSize: 13,
    textAlign: 'center',
  },
});

export default styles;
